# Generated by Django 2.2.7 on 2019-11-11 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250)),
                ('vote_count', models.IntegerField(default=0)),
                ('views', models.CharField(max_length=20)),
                ('tags', models.CharField(max_length=250)),
            ],
        ),
    ]
